# Generated by Django 3.2.9 on 2022-12-21 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='room_status',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('room_status_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='status_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp3.room')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp3.status')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp3.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp3.teacher'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp3.room_status'),
        ),
    ]
