# Generated by Django 3.2.9 on 2022-12-21 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp3.teacher'),
        ),
    ]
