# Generated by Django 3.2.9 on 2022-12-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roomlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Siratuti',
            fields=[
                ('room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('datatime', models.DateTimeField(auto_now_add=True, null=True)),
                ('zyoukyou1', models.CharField(max_length=100)),
            ],
        ),
    ]
